/* The catalogue uses the exported kit; hash routes also work from a local file. */
(() => {
const content=document.querySelector('.gallery-content'), scroll=document.getElementById('gallery-scroll');
const sections=[...content.querySelectorAll(':scope > section')];
const oldComponents=document.getElementById('components');
const entries=[];
function add(id,name,html,api,keyboard,react='') { entries.push({id,name,html,api,keyboard,react}); }
add('button','Buttons','<div class="sl-row"><button class="sl-btn primary">Primary</button><button class="sl-btn">Secondary</button><button class="sl-btn ghost">Ghost</button><button class="sl-btn small">Small</button><button class="sl-btn large">Large</button><button class="sl-btn danger">Danger</button><button class="sl-btn" disabled>Disabled</button></div>','sl-btn; primary, ghost, small, large, danger, icon. Use type="button" outside submission actions.','Tab focuses enabled buttons. Enter and Space activate.','<Button variant="primary" onClick={save}>Save changes</Button>');
add('input','Inputs','<label class="sl-field">Workspace name<input class="sl-input" placeholder="My workspace"><small>Choose a recognizable name.</small></label><label class="sl-field">Invalid value<input class="sl-input" aria-invalid="true" aria-describedby="input-error" value=""><small id="input-error">Enter a workspace name.</small></label><label class="sl-field">Disabled<input class="sl-input" disabled value="Unavailable"></label>','sl-input on native input or textarea. aria-invalid and associated error explain validation. Application owns validation.','Tab focuses; native editing keys remain available.','<Input placeholder="Workspace name" />');
add('field','Fields','<label class="sl-field">Folder<input class="sl-input" value="Personal"><small>Label, control, then supporting hint.</small></label>','sl-field wraps its native label and control. Use aria-describedby for essential hints.','Click label focuses its control.','<Field label="Folder" hint="Choose a folder."><Input /></Field>');
add('switch','Switches','<div class="sl-stack"><label class="sl-row"><input type="checkbox" role="switch" class="sl-switch" checked>Notifications</label><label class="sl-row"><input type="checkbox" role="switch" class="sl-switch">Automatic updates</label><label class="sl-row"><input type="checkbox" role="switch" class="sl-switch" disabled>Unavailable</label></div>','sl-switch on a native checkbox with role="switch". Read checked through the change event.','Tab and Space toggle enabled switches.');
add('checkbox','Checkboxes','<div class="sl-stack"><label class="sl-row"><input class="sl-check" type="checkbox" checked>Remember preference</label><label class="sl-row"><input class="sl-check" type="checkbox">Include archived items</label><label class="sl-row"><input class="sl-check" type="checkbox" disabled>Unavailable</label></div>','sl-check on a native checkbox. Application owns checked or indeterminate state.','Tab and Space toggle.');
add('panel','Panels','<section class="sl-panel"><div class="sl-panel-head"><h3>Workspace</h3><span class="sl-hint">Local</span></div><p class="sl-muted">Group related content without additional outlines.</p></section>','sl-panel and sl-panel-head group content. sl-row/sl-stack arrange controls.','Panels are structural; only their interactive descendants receive focus.','<Panel><h3>Workspace</h3></Panel>');
const menu=(select=false)=>`<div class="sl-popover-host"><button class="sl-btn" data-sl-menu="detail-options" aria-controls="detail-options" aria-haspopup="${select?'listbox':'menu'}" aria-expanded="false"><span data-sl-selected>${select?'Personal':'Open menu'}</span></button><div class="sl-menu" id="detail-options" role="${select?'listbox':'menu'}" aria-label="Workspaces" hidden><div data-sl-hover>${['Personal','Shared','Archived'].map((text,i)=>`<button class="sl-menu-row" role="${select?'option':'menuitem'}" ${select?`aria-selected="${i===0}"`:''} data-sl-row data-sl-value="${text.toLowerCase()}">${text}</button>`).join('')}</div></div></div>`;
add('menu','Menus',menu(),'data-sl-menu targets an sl-menu. sl-menu-row supports data-sl-value. slate:select bubbles on the trigger with detail.value.','Enter/Space opens. Up/Down, Home/End move focus. Escape returns focus. Tab leaves.','<MenuRow onClick={openWorkspace}>Personal</MenuRow>');
add('select','Selects',menu(true),'Use aria-haspopup="listbox", role="option", aria-selected and data-sl-selected. slate:select reports the value.','Arrow keys open/navigate; Enter selects; Escape closes.');
add('hover-list','Hover lists','<div class="sl-menu sl-scroll" data-sl-scroll-fade><div data-sl-hover><button class="sl-menu-row" data-sl-row>Personal</button><button class="sl-menu-row" data-sl-row>Shared</button><div style="height:8px"></div><button class="sl-menu-row" data-sl-row>Archived</button><button class="sl-menu-row" data-sl-row>Recent</button><button class="sl-menu-row" data-sl-row>Favorites</button><button class="sl-menu-row" data-sl-row>Downloads</button></div></div>','data-sl-hover container and data-sl-row descendants. One travelling surface; gaps preserve it, leaving releases it.','Tab focus follows the same highlight.','<HoverList><MenuRow>Personal</MenuRow><MenuRow>Shared</MenuRow></HoverList>');
add('tooltip','Tooltips','<div class="sl-row"><button class="sl-btn icon" aria-label="Play" data-sl-tooltip="Play"><svg class="sl-icon" data-sl-icon="play" aria-hidden="true"></svg></button><button class="sl-btn icon" aria-label="Copy" data-sl-tooltip="Copy"><svg class="sl-icon" data-sl-icon="copy" aria-hidden="true"></svg></button><button class="sl-btn icon" aria-label="Preferences" data-sl-tooltip="Preferences"><svg class="sl-icon" data-sl-icon="settings" aria-hidden="true"></svg></button></div>','data-sl-tooltip on the actual control. No title. Shared tooltip links aria-describedby while visible.','Focus shows immediately; Escape dismisses. Hover starts after 350ms.');
add('dialog','Dialogs','<button class="sl-btn" data-sl-dialog="detail-dialog">Open dialog</button><dialog id="detail-dialog" class="sl-dialog" aria-labelledby="detail-dialog-title"><h2 id="detail-dialog-title">Workspace preferences</h2><p>Preview only; no settings are saved.</p><label class="sl-field">Name<input class="sl-input" value="Personal" autofocus></label><div class="sl-dialog-actions"><button class="sl-btn ghost" data-sl-dialog-close>Cancel</button><button class="sl-btn primary" data-sl-dialog-close>Close preview</button></div></dialog>','data-sl-dialog, data-sl-dialog-close; SlateUI.closeDialog(dialog, returnValue). Browser focus trap remains during animated closing.','Tab stays inside; Escape closes and restores trigger focus.');
add('status','Status','<div class="sl-row"><span class="sl-status">Ready</span><span class="sl-status success">Connected</span><span class="sl-status warning">Processing</span><span class="sl-status error">Needs attention</span></div>','sl-status with success/warning/error. Include text so meaning does not depend on color. Add role="status" only for live updates.','Static status is readable without keyboard focus.','<Status tone="success">Connected</Status>');
add('notice','Notices','<div class="sl-stack"><div class="sl-notice">Choose a workspace to continue.</div><div class="sl-notice success">Preview state: complete.</div><div class="sl-notice error">Connection unavailable. Try again.</div></div>','sl-notice; success/error. Applications supply honest messages and recovery actions.','Focus recovery actions where supplied.');
add('progress','Progress','<label class="sl-field">Model download<progress class="sl-progress" value="64" max="100">64%</progress><small>64% complete</small></label><label class="sl-field">Waiting for response<progress class="sl-progress">Loading</progress></label>','Native progress supports determinate value/max or indeterminate without value. Label required.','Progress is read as status; no keyboard input.');
add('slider','Sliders','<label class="sl-field">Playback position<input class="sl-range" type="range" min="0" max="100" value="38"><small>Native range semantics.</small></label>','sl-range on input type="range". Set min/max/step and an accessible label; connect input event to actual state.','Arrows adjust; Home/End jump to limits.');
const iconNames=['play','pause','mic','settings','grid','layers','palette','pointer','panel','copy','book','download','check','close','minus','square','chevron','code','search','stop'];
add('icon','Icons','<div class="sl-stack"><div class="sl-row"><button type="button" class="sl-btn" aria-label="Play icon state" aria-pressed="false" data-sl-icon-toggle="play pause"><svg class="sl-icon" data-sl-icon="play" aria-hidden="true"></svg><span>Toggle Play / Pause</span></button></div><p class="sl-hint">Toggle the icon to inspect its state transition.</p><div class="icon-preview-grid">'+iconNames.map(name=>'<div class="icon-preview-item"><svg class="sl-icon" data-sl-icon="'+name+'" aria-hidden="true"></svg><span>'+name+'</span></div>').join('')+'</div></div>','sl-icon and data-sl-icon. SlateUI.setIcon(svg, name). data-sl-icon-toggle="play pause" previews two icon states without starting media playback. Original rounded Material Symbols geometry crossfades on state changes.','Owning controls need labels; decorative SVGs use aria-hidden. Enter and Space toggle the example.','<Icon name={playing ? "pause" : "play"} />');
const tabs=`<div class="sl-tabs" data-sl-tabs role="tablist" aria-label="Workspace view"><button class="sl-tab" id="tab-personal" role="tab" aria-selected="true" aria-controls="panel-personal" data-sl-value="personal">Personal</button><button class="sl-tab" id="tab-shared" role="tab" aria-selected="false" aria-controls="panel-shared" tabindex="-1" data-sl-value="shared">Shared</button><button class="sl-tab" role="tab" aria-selected="false" tabindex="-1" disabled>Unavailable</button></div><div class="sl-tabpanel" id="panel-personal" role="tabpanel" aria-labelledby="tab-personal" tabindex="0">Your personal workspace.</div><div class="sl-tabpanel" id="panel-shared" role="tabpanel" aria-labelledby="tab-shared" tabindex="0" hidden>Shared workspace content.</div>`;
add('tabs','Tabs / segmented control',tabs,'sl-tabs/data-sl-tabs with role="tablist"; sl-tab/role="tab" and aria-controls target labelled sl-tabpanel. One selected tab has tabindex=0. slate:tab bubbles with detail.value. Use vertical orientation with Up/Down.','Left/Right (or Up/Down vertically), Home/End activate and focus enabled tabs. Tab enters the selected panel.');
add('accordion','Accordion','<div class="sl-accordion"><details open><summary>What ships in the kit?</summary><div>CSS, portable interactions, fonts and templates.</div></details><details><summary>Can I use React?</summary><div>The optional adapter exports primitives; native markup works too.</div></details><details><summary>Does this connect a backend?</summary><div>Your application owns data and services.</div></details></div>','sl-accordion wraps native details/summary; open sets initial state. Independent sections allow multiple open. Native semantics work before JavaScript loads.','Tab focuses each summary. Enter or Space expands/collapses.');
add('skeleton','Skeleton','<div id="skeleton-preview" class="sl-stack" role="status" aria-live="polite"><div aria-hidden="true"><span class="sl-skeleton avatar"></span><span class="sl-skeleton"></span><span class="sl-skeleton short"></span></div><span class="sl-hint">Loading preview</span></div><button class="sl-btn" data-skeleton-toggle>Show loaded preview</button>','sl-skeleton, short, avatar. Hide shapes from assistive technology; mark the actual content aria-busy while loading. Replace with real data or a real error when its request completes.','Loading shapes are not focusable. Reduced motion stops pulsing.');
add('toast','Toasts','<div class="sl-row"><button class="sl-btn" data-toast-tone="success">Show success preview</button><button class="sl-btn" data-toast-tone="error">Show error preview</button><button class="sl-btn" data-toast-action>Show action preview</button><button class="sl-btn ghost" data-toast-clear>Dismiss all</button></div>','SlateUI.toast(message, { root, tone, duration, action: { label, onClick } }) returns {dismiss, element}. dismissToasts(root) clears. Default duration 5000ms; errors/actions persist (0). Hover/focus pauses timer; init disposer clears its root.','Tab reaches actions and dismiss. Escape dismisses the focused toast. Status uses polite announcements; errors use alert.');
add('workspace','Workspace / sidebar','<p class="sl-muted">The standalone template demonstrates the actual shell, sidebar, collapse control and contextual pages.</p><a class="sl-btn" href="templates/workspace.html">Open workspace preview</a>','sl-shell, sl-sidebar, sl-brand, sl-nav-row, sl-topbar, sl-workspace, sl-main-scroll. data-sl-collapse changes sl-collapsed and accessible state.','Tab navigates links and collapse control. Sidebar icons stay fixed while folding.');
add('window-controls','Window controls','<div class="sl-windowbar"><span>Window controls are UI demos</span><div class="sl-window-actions"><button class="sl-window-control" aria-label="Minimize demo" data-demo-action="Demo only. Connect to the desktop host."><svg class="sl-icon" data-sl-icon="minus" aria-hidden="true"></svg></button><button class="sl-window-control" aria-label="Maximize demo" data-demo-action="Demo only. Connect to the desktop host."><svg class="sl-icon" data-sl-icon="square" aria-hidden="true"></svg></button><button class="sl-window-control close" aria-label="Close demo" data-demo-action="Demo only. Connect to the desktop host."><svg class="sl-icon" data-sl-icon="close" aria-hidden="true"></svg></button></div></div>','sl-windowbar, sl-window-actions, sl-window-control. Wire to host APIs with necessary permissions. See examples/tauri-window.tsx.','Tab and Enter/Space activate host controls.');
add('overlay','Overlay','<p class="sl-muted">A compact transcript, status, meter and actions layout.</p><a class="sl-btn" href="templates/overlay.html">Open overlay preview</a>','Use templates/overlay.html. Host dimensions and recording services remain application responsibilities.','Template includes focusable transcript and accessible actions.');
add('scrollbar','Scrollbars','<div class="sl-scroll" data-sl-scroll-fade tabindex="0" aria-label="Scrollable example">'+Array.from({length:12},(_,i)=>`<p>Workspace item ${i+1}</p>`).join('')+'</div>','sl-scroll provides a bounded vertical viewport; kit scrollbar styling applies to Slate roots.','Focus viewport; arrows, Page Up/Down and Space scroll.');
add('text-arrival','Character arrival','<div id="detail-arrival" data-sl-text>Ready when you are.</div><button class="sl-btn" data-detail-arrival>Replay arrival</button>','data-sl-text; SlateUI.popInText(element). Graphemes remain intact; reduced motion shows plain text immediately.','Replay button supports Enter and Space.');
add('row-reveal','Row reveal','<div class="sl-stack" id="detail-reveal" data-sl-reveal><span>Personal workspace</span><span>Shared workspace</span><span>Archived workspace</span></div><button class="sl-btn" data-detail-reveal>Replay reveal</button>','data-sl-reveal; SlateUI.reveal(container) returns a cancellation function. Use after rendering a route.','Replay is keyboard accessible; rows remain semantic text.');
const purposes={
 button:'Trigger a primary or secondary action.',input:'Enter and validate text.',field:'Connect a label, control and hint.',switch:'Turn a setting on or off.',checkbox:'Select independent options.',panel:'Group related workspace content.',menu:'Choose an action from a floating surface.',select:'Choose one value from a custom list.',
 'hover-list':'Follow rows with a travelling highlight.',tooltip:'Explain compact controls on hover or focus.',dialog:'Keep a decision in a focused modal.',status:'Show the current state in a compact label.',notice:'Explain feedback and recovery inline.',progress:'Show completed work or a pending request.',slider:'Adjust a value within a range.',icon:'Communicate actions with rounded SVGs.',tabs:'Switch between related contextual views.',accordion:'Expand supporting content on demand.',skeleton:'Reserve space while real content loads.',toast:'Announce feedback with optional recovery.',workspace:'Organize contextual pages in a sidebar.',
 'window-controls':'Connect window actions to a desktop host.',overlay:'Keep transcript and actions close together.',scrollbar:'Navigate a bounded content viewport.',
 'text-arrival':'Introduce changed text character by character.','row-reveal':'Introduce a sequence of content rows.'
};
const miniature={
 menu:'<div class="sl-menu"><span class="sl-menu-row">Personal workspace</span><span class="sl-menu-row">Shared workspace</span></div>',
 select:'<span class="sl-btn">Personal workspace <svg class="sl-icon" data-sl-icon="chevron" aria-hidden="true"></svg></span>',
 tooltip:'<div class="catalogue-tooltip"><span class="sl-btn icon"><svg class="sl-icon" data-sl-icon="copy" aria-hidden="true"></svg></span><span class="sl-tooltip visible">Copy text</span></div>',
 dialog:'<div class="sl-dialog catalogue-dialog"><h3>Remove this item?</h3><p>You can keep it instead.</p><div class="sl-row"><span class="sl-btn ghost small">Cancel</span><span class="sl-btn primary small">Remove</span></div></div>',
 toast:'<div class="sl-toast"><span>Changes saved.</span><span class="sl-btn icon small"><svg class="sl-icon" data-sl-icon="close" aria-hidden="true"></svg></span></div>',
 workspace:'<div class="catalogue-workspace"><div class="sl-nav"><span class="sl-nav-row" aria-current="page"><svg class="sl-icon" data-sl-icon="grid" aria-hidden="true"></svg>Overview</span><span class="sl-nav-row"><svg class="sl-icon" data-sl-icon="settings" aria-hidden="true"></svg>Settings</span></div><div class="sl-panel"><span class="sl-status success">Ready</span><p>Your workspace</p></div></div>',
 overlay:'<div class="mini-overlay"><div class="mini-overlay-head"><strong>Transcript</strong><span class="sl-status">Ready</span></div><div class="mini-transcript">Your words appear here.</div><span class="sl-btn primary small">Start dictation</span></div>',
 'text-arrival':'<div class="catalogue-arrival"><span>Ready when you are.</span><small class="sl-hint">Character arrival</small></div>',
 'row-reveal':'<div class="sl-stack"><span class="sl-menu-row">Personal workspace</span><span class="sl-menu-row">Shared workspace</span><span class="sl-menu-row">Archived workspace</span></div>'
};
Object.assign(miniature,{
 button:'<span class="sl-btn primary">Save changes</span>',
 input:'<label class="sl-field">Name<input class="sl-input" value="Personal"></label>',
 field:'<label class="sl-field">Folder<input class="sl-input" value="Personal"><small>Choose a folder.</small></label>',
 switch:'<label class="sl-row"><input class="sl-switch" type="checkbox" checked>Notifications</label>',
 checkbox:'<label class="sl-row"><input class="sl-check" type="checkbox" checked>Remember preference</label>',
 panel:'<div class="sl-panel"><div class="sl-panel-head"><h3>Workspace</h3></div><span class="sl-muted">Related content</span></div>',
 'hover-list':'<div class="sl-menu"><span class="sl-menu-row">Personal workspace</span><span class="sl-menu-row catalogue-selected">Shared workspace</span></div>',
 status:'<span class="sl-status success">Connected</span>',
 notice:'<div class="sl-notice error">Connection unavailable.</div>',
 progress:'<label class="sl-field">Download<progress class="sl-progress" value="64" max="100">64%</progress><small>64% complete</small></label>',
 slider:'<label class="sl-field">Playback position<input class="sl-range" type="range" value="38"></label>',
 icon:'<div class="sl-row"><svg class="sl-icon" data-sl-icon="play" aria-hidden="true"></svg><svg class="sl-icon" data-sl-icon="mic" aria-hidden="true"></svg><svg class="sl-icon" data-sl-icon="settings" aria-hidden="true"></svg></div>',
 tabs:'<div class="sl-tabs"><span class="sl-tab catalogue-selected">Personal</span><span class="sl-tab">Shared</span></div>',
 accordion:'<div class="sl-accordion"><details open><summary>What ships?</summary><div>CSS, fonts and templates.</div></details></div>',
 skeleton:'<div class="sl-stack"><span class="sl-skeleton avatar"></span><span class="sl-skeleton"></span><span class="sl-skeleton short"></span></div>',
 'window-controls':'<div class="sl-window-actions"><span class="sl-window-control"><svg class="sl-icon" data-sl-icon="minus" aria-hidden="true"></svg></span><span class="sl-window-control"><svg class="sl-icon" data-sl-icon="square" aria-hidden="true"></svg></span><span class="sl-window-control close"><svg class="sl-icon" data-sl-icon="close" aria-hidden="true"></svg></span></div>',
 scrollbar:'<div class="sl-scroll catalogue-scroll-sample"><p>Personal workspace</p><p>Shared workspace</p><p>Archived workspace</p><p>Recent workspace</p></div>'
});
function createMiniature(entry){
 const visual=document.createElement('div');visual.className='catalogue-preview';visual.inert=true;visual.setAttribute('aria-hidden','true');
 visual.innerHTML=miniature[entry.id] || entry.html;
 visual.querySelectorAll('button,a,summary').forEach(control=>{const span=document.createElement('span');span.className=control.className;span.innerHTML=control.innerHTML;if(control.getAttribute('aria-selected')==='true')span.classList.add('catalogue-selected');control.replaceWith(span);});
 visual.querySelectorAll('*').forEach(node=>{for(const attr of [...node.attributes])if(attr.name==='id'||attr.name==='autofocus'||attr.name==='role'||attr.name==='tabindex'||attr.name.startsWith('aria-')||attr.name.startsWith('data-')&&attr.name!=='data-sl-icon')node.removeAttribute(attr.name);if(node.matches('input,textarea,select')){node.disabled=true;node.tabIndex=-1;}});
 const sample=document.createElement('div');sample.className='catalogue-sample';while(visual.firstChild)sample.append(visual.firstChild);visual.append(sample);return visual;
}
const catalogue=document.createElement('div');catalogue.className='catalogue-grid';
oldComponents.replaceChildren();const heading=document.createElement('div');heading.className='section-heading';heading.innerHTML='<h2>Components</h2><p>Explore the controls and patterns in the kit.</p>';
const toolbar=document.createElement('div');toolbar.className='catalogue-toolbar';toolbar.innerHTML='<label class="sl-field catalogue-search">Search components<input class="sl-input" type="search" placeholder="Name or purpose" aria-controls="component-results" id="component-search"></label><div class="sl-tabs catalogue-views" data-sl-tabs role="group" aria-label="Catalogue layout"><button class="sl-tab" type="button" data-catalogue-view="tiles" data-sl-value="tiles" aria-pressed="true"><svg class="sl-icon" data-sl-icon="grid" aria-hidden="true"></svg>Tiles</button><button class="sl-tab" type="button" data-catalogue-view="list" data-sl-value="list" aria-pressed="false"><svg class="sl-icon" data-sl-icon="panel" aria-hidden="true"></svg>List</button></div>';
catalogue.id='component-results';const count=document.createElement('p');count.className='sl-hint catalogue-count';count.setAttribute('role','status');const empty=document.createElement('div');empty.className='sl-notice catalogue-empty';empty.hidden=true;empty.textContent='No matching components. Try another name or purpose.';
oldComponents.append(heading,toolbar,count,catalogue,empty);
const cards=[];
for(const entry of entries){entry.purpose=purposes[entry.id];const link=document.createElement('a');link.className='sl-panel catalogue-link';link.href=`#components/${entry.id}`;link.setAttribute('aria-label',`${entry.name}. ${entry.purpose}`);const text=document.createElement('div');text.className='catalogue-card-copy';const name=document.createElement('strong');name.textContent=entry.name;const purpose=document.createElement('span');purpose.className='sl-muted';purpose.textContent=entry.purpose;text.append(name,purpose);link.append(createMiniature(entry),text);catalogue.append(link);cards.push({entry,link});}
// Fit one curated representative into every frame, including narrow list thumbnails.
const miniatureResize=new ResizeObserver(records=>records.forEach(({target})=>{const scale=Math.min(1,(target.clientWidth-24)/200,(target.clientHeight-16)/120);target.style.setProperty('--miniature-scale',String(Math.max(.1,scale)));}));
catalogue.querySelectorAll('.catalogue-preview').forEach(visual=>miniatureResize.observe(visual));
window.addEventListener('pagehide',()=>miniatureResize.disconnect(),{once:true});
const search=toolbar.querySelector('input');
function filterCatalogue(){const terms=search.value.toLowerCase().trim().split(/\s+/).filter(Boolean);let matches=0;for(const {entry,link} of cards){const haystack=`${entry.name} ${entry.purpose} ${entry.api}`.toLowerCase();const visible=terms.every(term=>haystack.includes(term));link.hidden=!visible;if(visible)matches++;}count.textContent=`${matches} of ${entries.length} components`;empty.hidden=matches!==0;}
search.addEventListener('input',filterCatalogue);filterCatalogue();
function setCatalogueView(view){const selected=view==='list'?'list':'tiles';catalogue.classList.toggle('catalogue-list',selected==='list');toolbar.querySelectorAll('[data-catalogue-view]').forEach(button=>{const active=button.dataset.catalogueView===selected;button.setAttribute('aria-pressed',String(active));button.tabIndex=active?0:-1;});try{localStorage.setItem('slate-catalogue-view',selected);}catch{}}
let savedView='tiles';try{savedView=localStorage.getItem('slate-catalogue-view')||'tiles';}catch{}setCatalogueView(savedView);
toolbar.addEventListener('slate:tab',event=>{if(event.target.matches('.catalogue-views'))setCatalogueView(event.detail.value);});
const detail=document.createElement('section');detail.id='component-detail';content.insertBefore(detail,content.querySelector('.gallery-footer'));
function block(title,text){const panel=document.createElement('div');panel.className='sl-panel';const h=document.createElement('h3');h.textContent=title;const p=document.createElement('p');p.className='sl-muted';p.textContent=text;panel.append(h,p);return panel;}
function codeBlock(title,code){const panel=block(title,'');const row=document.createElement('div');row.className='sl-panel-head';const h=panel.querySelector('h3');const button=document.createElement('button');button.className='sl-btn ghost small';button.innerHTML='<svg class="sl-icon" data-sl-icon="copy" aria-hidden="true"></svg><span>Copy code</span>';button.addEventListener('click',()=>copy(code,button));row.append(h,button);panel.replaceChildren(row);const pre=document.createElement('pre');pre.className='demo-code';pre.textContent=code;panel.append(pre);return panel;}
function integrationSwitcher() {
  const panels=[...detail.querySelectorAll(':scope > .sl-panel')].filter(panel=>panel.querySelector('pre') || panel.querySelector('h3')?.textContent==='React usage');
  if (!panels.length) return;
  const section=document.createElement('section');section.className='sl-panel integration-examples';
  const head=document.createElement('div');head.className='sl-panel-head';
  const heading=document.createElement('h3');heading.textContent='Integration example';
  const copyButton=document.createElement('button');copyButton.className='sl-btn ghost small';copyButton.innerHTML='<svg class="sl-icon" data-sl-icon="copy" aria-hidden="true"></svg><span>Copy code</span>';
  head.append(heading,copyButton);
  const tabs=document.createElement('div');tabs.className='sl-tabs';tabs.dataset.slTabs='';tabs.setAttribute('role','tablist');tabs.setAttribute('aria-label','Code format');
  section.append(head,tabs);
  for (const [index,panel] of panels.entries()) {
    const format=panel.querySelector('h3').textContent==='React usage'?'React':panel.querySelector('h3').textContent;
    const tab=document.createElement('button');tab.type='button';tab.className='sl-tab';tab.id=`code-tab-${format.toLowerCase()}`;tab.setAttribute('role','tab');tab.setAttribute('aria-selected',String(index===0));tab.setAttribute('aria-controls',`code-panel-${format.toLowerCase()}`);tab.tabIndex=index===0?0:-1;tab.textContent=format;tabs.append(tab);
    const view=document.createElement('div');view.className='sl-tabpanel';view.id=tab.getAttribute('aria-controls');view.setAttribute('role','tabpanel');view.setAttribute('aria-labelledby',tab.id);view.tabIndex=0;view.hidden=index!==0;
    const code=panel.querySelector('pre');if(code)view.append(code);else {const guidance=panel.querySelector('p');view.append(guidance);}
    section.append(view);panel.remove();
  }
  function syncCopy(){copyButton.disabled=!section.querySelector('.sl-tabpanel:not([hidden]) pre');}
  tabs.addEventListener('slate:tab',syncCopy);
  copyButton.addEventListener('click',()=>{const code=section.querySelector('.sl-tabpanel:not([hidden]) pre');if(code)copy(code.textContent,copyButton);});
  syncCopy();detail.append(section);
}
function documentationLayout(entry){
 const head=detail.firstElementChild;head.className='component-doc-head';head.replaceChildren();
 const back=document.createElement('a');back.href='#components';back.className='sl-muted component-doc-back';back.textContent='All components';
 const title=document.createElement('h1');title.textContent=entry.name;
 const purpose=document.createElement('p');purpose.className='component-doc-purpose';purpose.textContent=entry.purpose;
 const metadata=document.createElement('p');metadata.className='component-doc-meta';metadata.textContent=`@local/slate-ui · ${SlateUI.version} · ${entry.react?'HTML and React':'Portable HTML'}`;
 head.append(back,title,purpose,metadata);
 const preview=detail.querySelector('.component-preview');preview.classList.remove('sl-panel');
 const stage=document.createElement('section');stage.className='component-test-stage';stage.setAttribute('aria-label',`${entry.name} interactive preview`);
 const label=document.createElement('div');label.className='component-test-label';label.textContent='Interactive preview';stage.append(label,preview);
 const panels=[...detail.querySelectorAll(':scope > .sl-panel')];
 const api=panels.find(panel=>panel.querySelector('h3')?.textContent==='API and integration');
 const keyboard=panels.find(panel=>panel.querySelector('h3')?.textContent==='Keyboard and accessibility');
 const integration=detail.querySelector('.integration-examples');
 const tabs=document.createElement('div');tabs.className='sl-tabs component-doc-tabs';tabs.dataset.slTabs='';tabs.setAttribute('role','tablist');tabs.setAttribute('aria-label',`${entry.name} documentation`);
 const overview=document.createElement('div');overview.className='sl-tabpanel component-doc-view';overview.id='component-overview';overview.setAttribute('role','tabpanel');overview.setAttribute('aria-labelledby','component-overview-tab');
 const properties=document.createElement('div');properties.className='sl-tabpanel component-doc-view';properties.id='component-properties';properties.setAttribute('role','tabpanel');properties.setAttribute('aria-labelledby','component-properties-tab');properties.hidden=true;properties.tabIndex=0;
 for(const [index,name] of ['Overview','Properties'].entries()){const tab=document.createElement('button');tab.type='button';tab.className='sl-tab';tab.id=`component-${name.toLowerCase()}-tab`;tab.setAttribute('role','tab');tab.setAttribute('aria-selected',String(index===0));tab.setAttribute('aria-controls',`component-${name.toLowerCase()}`);tab.tabIndex=index===0?0:-1;tab.textContent=name;tabs.append(tab);}
 const usage=document.createElement('section');usage.className='component-usage';const usageTitle=document.createElement('h2');usageTitle.textContent='Usage';const instruction=document.createElement('p');instruction.className='sl-muted';instruction.textContent='Initialise SlateUI on your application root and use the exported markup. Connect state changes to your application data; the preview demonstrates UI behavior.';usage.append(usageTitle,instruction,integration);
 overview.append(stage,usage);
 for(const panel of [api,keyboard]){panel.classList.remove('sl-panel');panel.classList.add('component-property-section');properties.append(panel);}
 const roles={
 'sl-btn':'Action control; native button semantics come from its element.', 'sl-input':'Text input or textarea with shared control styling.', 'sl-field':'Label, control and optional supporting hint.', 'sl-switch':'Native checkbox displayed as an on/off setting.', 'sl-check':'Native checkbox displayed as an independent selection.',
 'sl-panel':'Borderless surface grouping related content.', 'sl-panel-head':'Heading and optional actions for a grouped surface.', 'sl-menu':'Floating surface containing action or option rows.', 'sl-menu-row':'One action or option inside a menu.', 'sl-popover-host':'Positioning context for a trigger and its floating menu.', 'sl-status':'Compact state label with text and a colored indicator.', 'sl-notice':'Inline message explaining feedback or recovery.', 'sl-progress':'Native progress element showing a pending or measured task.', 'sl-range':'Native range input for a bounded value.', 'sl-icon':'SVG slot populated from the shared rounded icon source.', 'sl-tabs':'Container for a set of related view selectors.', 'sl-tab':'One selector with tab semantics and selected state.', 'sl-tabpanel':'Content associated with its selected tab.', 'sl-accordion':'Group of native details/summary disclosures.', 'sl-skeleton':'Visual placeholder hidden from assistive technology.', 'sl-dialog':'Native modal dialog with shared surface styling.', 'sl-dialog-actions':'Ordered Cancel and primary actions inside a dialog.', 'sl-scroll':'Bounded vertical content viewport.', 'sl-row':'Horizontal arrangement of related content.', 'sl-stack':'Vertical arrangement of related content.', 'sl-windowbar':'Window title and action arrangement.', 'sl-window-actions':'Group of host window actions.', 'sl-window-control':'One action wired to the desktop host by the application.'
 };
 const parts=[...new Set([...entry.html.matchAll(/class="([^"]+)"/g)].flatMap(match=>match[1].split(/\s+/)).filter(name=>roles[name]))];
 if(parts.length){const anatomy=document.createElement('section');anatomy.className='component-property-section';const h=document.createElement('h2');h.textContent='Anatomy';const table=document.createElement('table');table.className='rule-table component-anatomy';const caption=document.createElement('caption');caption.textContent='Parts used by the example markup';table.append(caption);const th=document.createElement('thead');th.innerHTML='<tr><th scope="col">Part</th><th scope="col">Purpose</th></tr>';const body=document.createElement('tbody');for(const part of parts){const row=document.createElement('tr');const token=document.createElement('td');const code=document.createElement('code');code.textContent=part;token.append(code);const meaning=document.createElement('td');meaning.textContent=roles[part];row.append(token,meaning);body.append(row);}table.append(th,body);anatomy.append(h,table);properties.append(anatomy);}
 detail.replaceChildren(head,tabs,overview,properties);
}
function updateBreadcrumb(entry,target,title){
 const nav=document.getElementById('gallery-breadcrumb');nav.replaceChildren();
 const home=document.createElement('a');home.href='#overview';home.textContent='Design system';nav.append(home);
 const separator=()=>{const span=document.createElement('span');span.className='breadcrumb-separator';span.setAttribute('aria-hidden','true');span.textContent='/';nav.append(span);};
 if(entry){separator();const components=document.createElement('a');components.href='#components';components.textContent='Components';nav.append(components);}
 separator();const current=document.createElement('span');current.id='current-section';current.setAttribute('aria-current','page');current.textContent=title;nav.append(current);
}
function route(){let hash;try{hash=decodeURIComponent(location.hash.slice(1)||'overview');}catch{hash='overview';}const [page,id]=hash.split('/');const entry=page==='components'&&id?entries.find(item=>item.id===id):null;const target=entry?detail:sections.find(section=>section.id===page)||sections[0];for(const section of [...sections,detail])section.hidden=section!==target;if(entry){detail.replaceChildren();const head=document.createElement('div');head.className='section-heading';head.innerHTML=`<div><a href="#components" class="sl-muted">All components</a><h2>${entry.name}</h2></div><p>Exported Slate primitives and actual interactions.</p>`;const preview=document.createElement('div');preview.className='sl-panel component-preview';preview.innerHTML=entry.html;detail.append(head,preview,block('API and integration',entry.api),block('Keyboard and accessibility',entry.keyboard),codeBlock('HTML',entry.html.replace(/ data-(?:demo-[\w-]+|toast-[\w-]+|skeleton-toggle|detail-arrival|detail-reveal)(?:="[^"]*")?/g,'')));if(entry.id==='toast')detail.append(codeBlock('JavaScript',`// Call after a real action; root must match SlateUI.init(root).
const notification = SlateUI.toast('Copied to clipboard.', { root: appRoot });
SlateUI.toast('Connection unavailable. Try again.', {
  root: appRoot, tone: 'error', duration: 0,
  action: { label: 'Retry', onClick: retryConnection }
});
notification.dismiss();
SlateUI.dismissToasts(appRoot);`));if(entry.id==='skeleton')detail.append(codeBlock('JavaScript',`// After the actual request resolves, replace pending shapes with real content.
contentRegion.setAttribute('aria-busy', 'false');
contentRegion.replaceChildren(renderResult(result));
contentRegion.classList.add('sl-content-arrive');
// On failure render an actionable error instead.`));if(entry.react)detail.append(codeBlock('React',`import { ${entry.id==='hover-list'?'HoverList, MenuRow':entry.id==='field'?'Field, Input':entry.name==='Buttons'?'Button':entry.name==='Inputs'?'Input':entry.name==='Panels'?'Panel':entry.name==='Menus'?'MenuRow':entry.name==='Status'?'Status':'Icon'} } from '@local/slate-ui/react';\n// Initialise useSlateUI(ref) and import the stylesheet in your app.\n${entry.react}`));else detail.append(block('React usage','Use this same native markup in JSX with className and useSlateUI(ref). No dedicated React wrapper is exported for this pattern.'));}
if(entry){integrationSwitcher();documentationLayout(entry);}
const title=entry?entry.name:target.id==='integration'?'Integration':target.id[0].toUpperCase()+target.id.slice(1);updateBreadcrumb(entry,target,title);document.title=`${title} — Slate UI`;document.querySelectorAll('#gallery-navigation a').forEach(link=>{if(link.hash===`#${entry?'components':target.id}`)link.setAttribute('aria-current','page');else link.removeAttribute('aria-current');});scroll.scrollTop=0;SlateUI.dismissToasts();if(location.hash){const h=target.querySelector('h1,h2');if(h){h.tabIndex=-1;h.focus({preventScroll:true});}}}
document.addEventListener('click',event=>{const b=event.target.closest('button');if(!b)return;if(b.hasAttribute('data-detail-arrival'))SlateUI.popInText(document.getElementById('detail-arrival'));if(b.hasAttribute('data-detail-reveal'))SlateUI.reveal(document.getElementById('detail-reveal'));if(b.dataset.toastTone)SlateUI.toast(b.dataset.toastTone==='error'?'Preview error: connection unavailable. Try again.':'Preview success: action completed.',{tone:b.dataset.toastTone});if(b.hasAttribute('data-toast-action'))SlateUI.toast('Action preview: item moved.',{action:{label:'Undo preview',onClick:()=>SlateUI.toast('Undo preview completed.')}});if(b.hasAttribute('data-toast-clear'))SlateUI.dismissToasts();if(b.hasAttribute('data-skeleton-toggle')){const node=document.getElementById('skeleton-preview');const loaded=b.textContent.startsWith('Show');node.innerHTML=loaded?'<strong>Personal workspace</strong><span class="sl-muted">Loaded preview content.</span>':'<div aria-hidden="true"><span class="sl-skeleton avatar"></span><span class="sl-skeleton"></span><span class="sl-skeleton short"></span></div><span class="sl-hint">Loading preview</span>';node.classList.remove('sl-content-arrive');void node.offsetWidth;node.classList.add('sl-content-arrive');b.textContent=loaded?'Reset loading preview':'Show loaded preview';}});
window.addEventListener('hashchange',route);route();
})();
